steps:
- name: node:18.13.0
  entrypoint: npm
  args: ["install"]
- name: node:18.13.0
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1600s"